// 商品图片静态映射（React Native require 不能动态拼接）
export const IMAGE_MAP = {
  rm01: require('../../assets/rm01.jpg'),
  rm02: require('../../assets/rm02.jpg'),
  rm03: require('../../assets/rm03.jpg'),
  zp01: require('../../assets/zp01.jpg'),
  zp02: require('../../assets/zp02.jpg'),
  zp03: require('../../assets/zp03.jpg'),
  sg01: require('../../assets/sg01.jpg'),
  sg02: require('../../assets/sg02.jpg'),
  sg03: require('../../assets/sg03.jpg'),
  sg04: require('../../assets/sg04.jpg'),
  sg05: require('../../assets/sg05.jpg'),
  sg06: require('../../assets/sg06.jpg'),
  sg07: require('../../assets/sg07.jpg'),
  sg08: require('../../assets/sg08.jpg'),
  cx01: require('../../assets/cx01.jpg'),
  cx02: require('../../assets/cx02.jpg'),
  cx03: require('../../assets/cx03.jpg'),
  sn01: require('../../assets/sn01.jpg'),
  sn02: require('../../assets/sn02.jpg'),
  sn03: require('../../assets/sn03.jpg'),
  sn04: require('../../assets/sn04.jpg'),
  sn05: require('../../assets/sn05.jpg'),
  sn06: require('../../assets/sn06.jpg'),
  sn07: require('../../assets/sn07.jpg'),
  sn08: require('../../assets/sn08.jpg'),
  xr01: require('../../assets/xr01.jpg'),
  xr02: require('../../assets/xr02.jpg'),
  xr03: require('../../assets/xr03.jpg'),
  xr04: require('../../assets/xr04.jpg'),
  xr05: require('../../assets/xr05.jpg'),
  xr06: require('../../assets/xr06.jpg'),
  xr07: require('../../assets/xr07.jpg'),
  xr08: require('../../assets/xr08.jpg'),
  jk01: require('../../assets/jk01.jpg'),
  jk02: require('../../assets/jk02.jpg'),
  jk03: require('../../assets/jk03.jpg'),
  jk04: require('../../assets/jk04.jpg'),
  jk05: require('../../assets/jk05.jpg'),
  jk06: require('../../assets/jk06.jpg'),
  jk07: require('../../assets/jk07.jpg'),
  xc01: require('../../assets/xc01.jpg'),
  xc02: require('../../assets/xc02.jpg'),
  xc03: require('../../assets/xc03.jpg'),
  xc04: require('../../assets/xc04.jpg'),
  xc05: require('../../assets/xc05.jpg'),
  xc06: require('../../assets/xc06.jpg'),
  xc07: require('../../assets/xc07.jpg'),
  xc08: require('../../assets/xc08.jpg'),
  xc09: require('../../assets/xc09.jpg'),
  xc10: require('../../assets/xc10.jpg'),
  xc11: require('../../assets/xc11.jpg'),
  xc12: require('../../assets/xc12.jpg'),
  xc13: require('../../assets/xc13.jpg'),
  xc14: require('../../assets/xc14.jpg'),
  xc15: require('../../assets/xc15.jpg'),
  xc16: require('../../assets/xc16.jpg'),
  xc17: require('../../assets/xc17.jpg'),
  g01: require('../../assets/g01.jpg'),
  g02: require('../../assets/g02.jpg')
};

export function getItemImage(itemOrKey) {
  const key = typeof itemOrKey === 'string' ? itemOrKey : itemOrKey?.image;
  if (key && IMAGE_MAP[key]) return IMAGE_MAP[key];
  return null;
}

